# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name=b'album_name')),
                ('album_pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name=b'member_name')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('events', models.CharField(max_length=60)),
                ('events_pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('members', models.ManyToManyField(to='app.Member')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='members',
            field=models.ManyToManyField(to='app.Member'),
        ),
    ]
